Updating Nginx and fixing Init file for VSFTPd.

diff --git a/modules/vsftpd/init.d/vsftpd b/modules/vsftpd/init.d/vsftpd
--- a/modules/vsftpd/init.d/vsftpd
+++ b/modules/vsftpd/init.d/vsftpd
@@ -1,68 +1,119 @@
 #! /bin/sh
-
 ### BEGIN INIT INFO
-# Provides:          vsftpd
+# Provides:          vfstpd
 # Required-Start:    $remote_fs $syslog
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: vsftpd init.d script for Ubuntu.
-# Description:       vsftpd init.d script for Ubuntu.
+# Short-Description: VSFTPD init script
+# Description:       File created for starting VSFTPD manually
+#                    installed on Ubuntu 12.04
 ### END INIT INFO
 
-. /lib/lsb/init-functions
-INSTALL_DIR="/usr/local"
-DAEMON="$INSTALL_DIR/sbin/vsftpd"
-CONFIG_FILE=/etc/vsftpd.conf
-DAEMON_OPTS=""
+PATH=/usr/local/sbin:/sbin:/usr/sbin:/bin:/usr/bin
+DESC="VSFTP Daemon"
 NAME=vsftpd
-DESC="FTP"
+DAEMON=/usr/local/sbin/$NAME
+DAEMON_ARGS=" "
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
-test -x $DAEMON || exit 0
+[ -x "$DAEMON" ] || exit 0
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+. /lib/init/vars.sh
+. /lib/lsb/init-functions
 
-set -e
+RED=$(tput setaf 1)
+GREEN=$(tput setaf 2)
+NORMAL=$(tput sgr0)
+
+col=80
+
+do_start() {
+  echo -n "* Starting vsftpd "
+  $DAEMON & >/dev/null 2>&1
+  if [ "$?" -eq "0" ]
+  then
+    printf '%*s[%s%s]\n' $col "$NORMAL" "OK" "$NORMAL"
+    pidof $NAME > $PIDFILE
+    return 0
+  else
+    printf '%*s[%s%s]\n' $col "$NORMAL" "${RED}fail" "$NORMAL"
+    return 2
+  fi
+}
+
+do_stop() {
+  echo -n "* Stopping vsftpd "
+  kill -KILL `cat $PIDFILE` >/dev/null 2>&1
+  if [ "$?" -eq "0" ]
+  then
+    rm -f $PIDFILE
+    printf '%*s[%s%s]\n' $col "$NORMAL" "OK" "$NORMAL"
+    return 0
+  else
+    printf '%*s[%s%s]\n' $col "$NORMAL" "${RED}fail" "$NORMAL"
+    return 2
+  fi
+}
+
+do_status() {
+  echo -n "* Service vsftpd is "
+  pidof $NAME >/dev/null 2>&1
+  if [ "$?" -eq "0" ]
+  then
+    echo "running"
+    return 0
+  else
+    echo "not running"
+    return 2
+  fi
+}
+
+do_reload() {
+  kill -HUP `cat $PIDFILE`
+  return 0
+}
 
 case "$1" in
   start)
-    log_daemon_msg "Starting $DESC" $NAME
-    if ! start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS ; then
-      log_end_msg 1
-    else
-      log_end_msg 0
-    fi
-  ;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    do_start
+    case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
   stop)
-    log_daemon_msg "Stopping $DESC" $NAME
-    if start-stop-daemon --quiet --stop --oknodo --retry 30 --pidfile $PIDFILE --exec $DAEMON; then
-      rm -f $PIDFILE
-      log_end_msg 0
-    else
-      log_end_msg 1
-    fi
-  ;;
-  reload)
-    log_daemon_msg "Reloading $DESC configuration" $NAME
-    if start-stop-daemon --stop --signal 2 --oknodo --retry 30 --quiet --pidfile $PIDFILE --exec $DAEMON; then
-    if start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS ; then
-      log_end_msg 0
-    else
-      log_end_msg 1
-    fi
-    else
-      log_end_msg 1
-    fi
-  ;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
+  status)
+   do_status
+   ;;
   restart|force-reload)
-    $0 stop
-    sleep 1
-    $0 start
-  ;;
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1)
+        do_start
+        case "$?" in
+          0) log_end_msg 0 ;;
+          1) log_end_msg 1 ;; # Old process is still running
+          *) log_end_msg 1 ;; # Failed to start
+        esac
+        ;;
+      *)
+        log_end_msg 1
+        ;;
+    esac
+    ;;
   *)
-  echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-  exit 1
+  echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+  exit 3
   ;;
 esac
-
-exit 0
